### PR TITLE
Mailman archive

### LINKED ISSUE #222: Incorporate cf-metadata mailman archive from UCAR into CF GitHub website
Dear all

The [CF UCAR email archive](http://mailman.cgd.ucar.edu/pipermail/cf-metadata) has vanished, in which our discussions occurred before we started to use GitHub. There's a broken link to it on the [discussion page](http://cfconventions.org/discussion.html). We had previously discussed that it would make sense to host the archive in GitHub. Luckily @davidhassell had downloaded it a while ago (as a plain-text file in Unix mailbox format). I have converted this to HTML [looking like this](http://www.met.rdg.ac.uk/~jonathan/CF_metadata/cf-metadata-mailman) and prepared a [pull request](https://github.com/cf-convention/cf-convention.github.io/pull/221) to include in the CF GitHub website instead of the broken link.

Does this look OK? Please note that this isn't finished yet because `faq.md` contains references to particular emails and I'll have to work out which ones they are. I have modified `discussion.md` and `governance.md`, I believe. However, this pull request contains so many files that I can't look at it. Also, the first automatic check failed. I would appreciate GitHub advice.

Best wishes

Jonathan

### PR DESCRIPTION
**Pull request by JonathanGregory**
Fixes #222

### CODE REVIEW

**Comment by davidhassell** [comment]
Thanks, Jonathan - could you possibly also update the `[archives]` link in `discussion.md` as part of this PR?

**Comment by davidhassell** [comment]
Dear Jonathan, I assumed that `discussion.md` and `goverance.md` hadn't been modified since when `Data/cf-metadata-mailman` is collapse in the "changed files" panel, no other files appear ... am I missing something?

**Comment by JonathanGregory** [comment]
I don't think it's showing us everything. When you collapse it, I don't believe it looks again at what there is, having already decided it's not going to show more than 3000 files.

**Comment by JonathanGregory** [comment]
You can see the files [here in my repo](https://github.com/JonathanGregory/cf-convention.github.io/tree/mailman-archive)

**Pull request closed without merging**
