### PR TITLE
1.9 documents

### PR DESCRIPTION
**Pull request by davidhassell**

### CODE REVIEW

**Comment by erget** [comment]
@davidhassell I merged this in order to get the HTML page up but I see that something's wrong with the PDF. I pulled it down and it looks like this:
```bash
erget@NB815149:~$ wget http://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.pdf
Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/home/erget/.wget-hsts'. HSTS will be disabled.
--2021-09-10 18:30:03--  http://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.pdf
Resolving cfconventions.org (cfconventions.org)... 185.199.109.153, 185.199.110.153, 185.199.108.153, ...
Connecting to cfconventions.org (cfconventions.org)|185.199.109.153|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 132 [application/pdf]
Saving to: ‘cf-conventions.pdf’

cf-conventions.pdf          100%[==========================================>]     132  --.-KB/s    in 0s

2021-09-10 18:30:03 (7.41 MB/s) - ‘cf-conventions.pdf’ saved [132/132]

erget@NB815149:~$ l -h cf-conventions.pdf
-rw-r--r-- 1 erget erget 132 Sep 10 18:24 cf-conventions.pdf
erget@NB815149:~$ cat cf-conventions.pdf
version https://git-lfs.github.com/spec/v1
oid sha256:f8ee1419afe6489ed9899914a775016176b24baa6f7a777205023cd0feaa9221
size 5461599
```

Looks like it's actually a LFS pointer rather than the object itself... Do you have a smart idea? I'm fiddling with it in parallel.

**Comment by erget** [comment]
Hmm. In the repo everything looks OK for me. Something we could do to hotfix would be to link to https://github.com/cf-convention/cf-convention.github.io/raw/master/Data/cf-conventions/cf-conventions-1.9/cf-conventions.pdf - that downloads directly from the repo. Unfortunately I'm having to run away now so I can't get make anything much smarter in the time I've got 😢

**Comment by ethanrd** [comment]
Agree. When I download the file in the conventions repo and the copy in the website repo:

- https://github.com/cf-convention/cf-conventions/blob/gh-pages/1.9.0/cf-conventions.pdf
- https://github.com/cf-convention/cf-convention.github.io/blob/master/Data/cf-conventions/cf-conventions-1.9/cf-conventions.pdf

they are identical. However, if I access them through the web pages, one successfully opens and the other fails:

- Succeeds: https://cfconventions.org/cf-conventions/1.9.0/cf-conventions.pdf
- Fails: https://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.pdf

**Comment by ethanrd** [comment]
If I download from failing web page URL, I get a 132 byte file. Here's what I see in the file

> version https://git-lfs.github.com/spec/v1
oid sha256:f8ee1419afe6489ed9899914a775016176b24baa6f7a777205023cd0feaa9221
size 5461599

Are we using [GitHub Large File Storage](https://git-lfs.github.com/) in the website GH Pages in some way?

I've never used GH LFS before so I will leave it here and see if anyone else understands what might be going on.

**Comment by ethanrd** [comment]
Sorry @erget ! I see I'm repeating what you said earlier.
Must read more carefully.

**Comment by erget** [comment]
Fixed this in fcf847e.

**Comment by erget** [comment]
Root cause: We had in `.gitattributes` the directive to LFS PDFs, which in general makes sense but in the case of the website does not, since those are artefacts that get put out onto the website. If we want to store them in LFS there's ways to do this, but then we'd have to update all of the links (easy enough to do, but I'd only do it if we start to have a space issue in the repo). I've changed the configuration committed in the repo and re-committed those PDFs that should have been in-repo, but instead were LFS objects. In this case, old-fashioned git is the way to go.

**Comment by davidhassell** [comment]
Fantastic! Thanks, @erget.

**Comment by ethanrd** [comment]
Yes. Thanks @erget.

**Pull request merged**
