### PR TITLE
New and unified version of schema file (.xsd) for XML standard names table

### PR DESCRIPTION
**Pull request by larsbarring**
This version of the schema file implements issue #459, i.e. recent changes to the XML formal as specified in Appendix B.

**This PR must be merged after PR #458**.

Only the [new file](https://github.com/cf-convention/cf-convention.github.io/pull/468/files#diff-bcc61478734955ecf4e2752e23518167d44c02fe863cb9b8e552f206181aea9e) is relevant for this PR. ~~All other changes belong to PR #458.~~ (Force pushed change to remove those files from this PR)

### CODE REVIEW

**Comment by DocOtak** [comment]
Should the xsd name space be versioned as 1.0 or 1.1? Looks like the spec says you don't need the version if you don't want to and that all 1.0 files should be valid 1.1.

**Comment by larsbarring** [comment]
I am not sure about which version to use because I focussed on making as few changes as possible. And from my testing is seems that version 1.0 worked as expected. I have no deeper insight into these matters, and if there are reasons to change I it would be simple to implement.

**Comment by ethanrd** [comment]
@DocOtak wrote:
> Should the xsd name space be versioned as 1.0 or 1.1? Looks like the spec says you don't need the version if you don't want to and that all 1.0 files should be valid 1.1.

Are you asking about the version in the name of the .xsd file? There does not appear to be an XML Namespace defined (the XSD does not specify a `targetNamespace` and the XML files use a `noNamespaceSchemaLocation` attribute to reference the .xsd file).

(I haven't been following this closely. Sorry if I missed earlier discussions.)

**Comment by larsbarring** [comment]
I am not (at all) an expert on these matters, but after having looked at https://www.w3.org/TR/xmlschema11-1/#ns-bindings, and it seems clear that all the namespace prefixes `xs` and `xsi` will have to be changed throughout the file. Of course this can be done, but I think that this is only warranted if we can establish a tangible advantage.

**Comment by ethanrd** [comment]
Hi @DocOtak and @larsbarring - I think the only reason to look at updating the XML Schema versions would be if newer versions had new features that we wanted to use in the standard names XSD files. I suspect we use pretty standard XML Schema capabilities so probably don't have any need to update.

Also, the referenced W3C document seems to be the latest version. And the "xs" and "xsi" namespace URLs in the CF standard name `.xsd and `.xml` files match what is listed in [Section 1.3.3 Conventional Namespace Bindings](https://www.w3.org/TR/xmlschema11-1/#ns-bindings):

- "xs=http://www.w3.org/2001/XMLSchema" and
- "xsi=http://www.w3.org/2001/XMLSchema-instance"

[It has been a long time since I've done much XSD work but these namespace URLs look very familiar.]

**Comment by DocOtak** [comment]
@ethanrd Only thing I can think of is if we decide that having some ordering to elements be in the schema, e.g. aliases must be in some lex sorted order, then I'm pretty sure that's a 1.1 feature

**Comment by ethanrd** [comment]
The referenced document is XML Schema 1.1 which is the latest version. So I would think we would be good with the namespaces specified in section 1.3.3. Though the "2001" in the URL when 1.1 was approved in 2012 seems odd. I expect it is a backward compatibility thing.

**Comment by larsbarring** [comment]
Hi @DocOtak and @ethanrd -- Thanks for these useful comments :-) However, as this conversation has moved on to deal more with the scope of the proposal as such (i.e. enforce/implement sorting or not) I suggest that we continue in the issue. Hence I have copied these comments over to [this issue comment](https://github.com/cf-convention/cf-convention.github.io/issues/459#issuecomment-2041006590), and also added my further thoughts in the next comment (over there).

**Pull request merged**
