### PR TITLE
Updated a broken link to UDUNITS examples of how to format units strings

### PR DESCRIPTION
**Pull request by larsbarring**
Cf. [Link Checker report #370](https://github.com/cf-convention/cf-convention.github.io/issues/370):

> ✗ [404] https://www.unidata.ucar.edu/software/udunits/udunits-current/udunits2lib.html#Examples | Failed: Network error: Not Found

### CODE REVIEW

**Comment by JonathanGregory** [comment]
Thanks for correcting this, @larsbarring. Please could you also put a line in the `history.adoc` as usual. It can refer to this PR, without an issue, since it's a small correction; you'll see that a few other lines in the history likewise refer to PRs.

**Comment by larsbarring** [comment]
Dear Jonathan, @JonathanGregory, as you are taking care of the link checker reports, I have put you as reviewer and eventually/possibly doing the merge. Of course, feel free to suggest, or transfer it to someone else.

Many thanks /Lars

**Comment by larsbarring** [comment]
@JonathanGregory I didn't notice that your comment popped in while I was typing. Is there a `history.adoc` for this repo (I could not find it)?

**Comment by JonathanGregory** [comment]
> @JonathanGregory I didn't notice that your comment popped in while I was typing. Is there a `history.adoc` for this repo (I could not find it)?

Oh no, of course not. Sorry! No need to do anything then.

**Pull request merged**
