### PR TITLE
Clarify RULES

### LINKED ISSUE #102: Refactor "rules"
The idea here is

1. Update "rules" to point to various CONTRIBUTING.md files for each repository.
1. Migrate the content of "errors" into "rules"
1. Spruce up rules for making changes to the CF Conventions in "rules", adding an activity diagram so that it doesn't seem so scary.

This supersedes the actions on @erget in #94 so that they can be tracked here, separate from the others.

Originally this issue was also intended to add CONTRIBUTING.md to this repository. This was done in f9ee1000cc4959aaad48b83cc75e189c751ac181 but now is being pursued in #121 and an associated issue (pending creation at this time).

### PR DESCRIPTION
**Pull request by erget**
Fixes #102.

### CODE REVIEW

**Comment by ethanrd** [comment]
@erget - I believe the @cf-convention/info-mgmt team is only visible to members of the cf-convention organization. The GitHub [Change Team Visibility](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/changing-team-visibility) page lists "visible" (to organization members) and "secret" (only team members). I'm not seeing a way to make it more broadly visible. So, perhaps reference the list on the governance.md page instead of the team?

**Comment by ethanrd** [comment]
Also, not sure why the check failed. Looks like it couldn't install one of the ruby gem dependencies for the Jekyll build:
> Fetching i18n 0.9.5
> Errno::EACCES: Permission denied @ rb_file_s_rename -
> (/home/jekyll/.gem/ruby/2.7.0/cache/i18n-0.9.5.gem, /usr/gem/cache/i18n-0.9.5.gem)
> An error occurred while installing i18n (0.9.5), and Bundler cannot continue.

I ran it a second time just in case it was a spurious failure. Alas, it failed again.

I will try to take a closer look later today, but I may not get to it till tomorrow.

**Comment by DocOtak** [comment]
@ethanrd Looks like there is some upstream issue with that GH action https://github.com/jerryjvl/jekyll-build-action/issues/1

**Comment by nigelbritton** [comment]
@DocOtak noticed you might be having the same issue I was. I made a fork/update which is available as a release should you wish to use it.

If you update https://https://github.com/cf-convention/cf-convention.github.io/blob/master/.github/workflows/check_jekyll_build.yml#L27 with this below your Jekyll build should work.
```
uses: nigelbritton/jekyll-build-action@v1.1
```

**Comment by erget** [comment]
@nigelbritton I tried that out in 34bda8b but it didn't seem to work... Do you know why?

**Comment by ethanrd** [comment]
Hi @erget - Not sure but you have 'v1' whereas @nigelbritton suggested 'v1.1'.

**Comment by erget** [comment]
Ugh noob error! Shame!

**Comment by ethanrd** [comment]
Thanks @erget - Looks like that fixed the build problem.
Thanks @nigelbritton for the help.

**Comment by erget** [comment]
@ethanrd gotta come to you with a noob question again...
I'm now building an activity diagram from [this](https://github.com/erget/erget.github.io/blob/master/cf-change-process.txt) and I see that it's working. I move the artefact to `Data/media/images` and can see that in the Action. If I download the built Jekyll site as an artefact I see it in there too.

That image should be embedded in [the rules page](https://erget.github.io/rules.html) but the image turns up a 404. Yet when I unzip the artefacts and go to the page locally it's there.

Now I've tried linking the image in using HTML (ungainly but should work)... And it doesn't. Looks like the relative local path doesn't work the same locally as it does on the web - locally it's fine, but no luck on the live site. Do you see what I'm doing wrong?

**Comment by DocOtak** [comment]
@erget The GH action is just set up for checking PRs, if you want that image to exist on the actual build (which is automatic by github itself), you'll need to include that image in the actual PR.

Technical aside, can the diagram be an SVG rather than PNG?

**Comment by erget** [comment]
@DocOtak bummer, but now I get it :D

I'll have it make an SVG instead.

**Comment by erget** [comment]
Alright. Notwithstanding the messy commit history I now can regenerate the diagrams and commit them if needed. This doesn't trigger a rebuild of the site though; it looks like [this would be possible to trigger via cronjob](https://github.com/marketplace/actions/jekyll-actions) but I won't try it at the moment because it looks like there I'd need to fiddle with tokens and the like.

**Comment by erget** [comment]
Come to think of it, it's not even that awful that the page doesn't get rebuilt, because
1. That diagram shouldn't get touched that often
1. It'll get committed into the fork and rebuilt by this repo's actions when the PR is sent with the asset committed in the action already stored, so the main page won't be affected

**Comment by ethanrd** [comment]
@erget - You could restrict the diagram build to only run when the diagram file(s) is changed with something like:
```
on:
  push:
    paths:
   - 'cf-change-process.txt'
```

Or in case we end up with more diagrams on the website, with a change to the file extension:
```
on:
  push:
    paths:
    - '**.plantuml'
```

**Comment by erget** [comment]
I seem not to be able to change the from branch but I've backed this up to 103-clarify-rules now. Shoulda used a topic branch from the get-go.

**Pull request merged**
