### PR TITLE
Adding meetings content for 2019, 2018, 2017 and 2016

### PR DESCRIPTION
**Pull request by cofinoa**
@ethanrd and @davidhassell I have added the agenda por CF past workshops (i.e. 2019, 2018, 2017 and 2016). 

@ethanrd for 2016 and 2017 I have attached notes and slides available at Unidata's events website. 

@davidhassell I have just copied the 2018 agenda you pass me. If you have the presentations and related docs I can attache them. 

I was planning to add other related meeting, but before I would like to merge these ones.

### CODE REVIEW

**Comment by ethanrd** [comment]
@cofinoa - Looks great. Thanks for putting this together. I think we could remove the Remote Participation, Travel, and Lodging sections in the two Boulder mtg pages. I will dig up any report/summary documents as well (for another PR).

**Comment by davidhassell** [comment]
Hi Antonio, great - thanks. @ethanrd we had a google doc on 2018 notes, I recall - I think they're were finished, right?

**Comment by cofinoa** [comment]
@ethanrd  I have removed the unwanted sections form 2016 and 2017 workshops. 

@ethanrd, BTW, please try to find the missing pdf, for the breakout session about CF-Radial on :
* Thursday, 7 September 2017
   * ...
   * 09:00 - Breakout Session Reports
     * CF-Radial – Mike Dixon (slides 404)

@davidhassell and @davidhassell all workshops have and empty section "Summary and Key Decisions" with the intention to attach a summary report from the respective meeting. If you can collect them we can add it in another PR.

**Comment by ethanrd** [comment]
@cofinoa - Looks good. I will merge this in and we can, as you suggest, add summaries and update summaries in other PRs. Thanks again!

**Pull request merged**
