### PR TITLE
Adding two new vertical coordianates from trac ticket 93, fixes #32

### LINKED ISSUE #32: Add new dimensionless vertical coordinates from Trac Ticket 93
The two new dimensionless vertical coordinates for ocean models from [Trac Ticket 93](http://cf-trac.llnl.gov/trac/ticket/93) have been approved for inclusion in CF-1.7, but do not yet appear in the draft document.   The [appendix-d.xml docbook](https://github.com/cf-convention/cf-convention.github.io/blob/master/Data/cf-conventions/cf-conventions-1.7/docbooksrc/appendix-d.xml) and the [docbook info/changes docbook](https://github.com/cf-convention/cf-convention.github.io/blob/master/Data/cf-conventions/cf-conventions-1.7/docbooksrc/the-book-info.xml) need to be modified.

### PR DESCRIPTION
**Pull request by rsignell-usgs**
Adding two new vertical coordinates from trac ticket 93, fixes #32.     I only modified the docbook source files.  Can someone who knows what they are doing run the processing scripts?  I couldn't figure that out.

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
@mattben, Did you run the processing scripts?

**Comment by mattben** [comment]
whoops, missed that part. @painter1 can you please run the updated scripts and then make a pull request please and thank you (or come show me how :stuck_out_tongue_closed_eyes:)

**Comment by painter1** [comment]
I just built the new versions of the documents.
There is one error that I noticed.

The new text (I think that's the two sections about ocean s-coordinate, generic form) must be surrounded by a <emphasis role="newtext"> tag.  There's now such a tag around the word "where", undoubtedly copied from the older section "Ocean s-coordinate".  This tag isn't needed in the new sections because the entire sections are tagged.

You may have noticed that I started a discussion of this practice on the cf-metadata list.  But for now it's official policy that we have to use such tags.

I'll write instructions about how to build the documents.  Basically, you type "make" :-).

**Comment by painter1** [comment]
For document build instructions, see
https://github.com/cf-convention/cf-convention.github.io/wiki/How-to-build-the-document-from-the-Docbook-sources

**Pull request merged**
