### PR TITLE
Add new members of CF Committee to list in the governance page.

### PR DESCRIPTION
**Pull request by ethanrd**
Three new members have been added to the CF Committee.

Could someone else from @cf-convention/gov-panel review and merge?

### CODE REVIEW

**Review by JonathanGregory — APPROVED** [review]
That looks right. Thanks, Ethan.

**Comment by JonathanGregory** [comment]
Thank you, Ethan. I've merged the change. It said some check about markdown had failed. J

**Comment by ethanrd** [comment]
Thanks Jonathan. Yes, I saw that error as well. I looks like the new link checking failed. I think that check was added recently by @erget? I'll also ping @cf-convention/info-mgmt in case anyone is already looking into this.

**Comment by erget** [comment]
Hello all, this is part of the glacial push to get the website free of broken links. Over time pushes should eliminate broken links rather than create new ones - that's what that check looks for. Now the check's in place, but the broken links it finds still need to be corrected. I don't think it's a problem for this PR because none of the broken links are in the edited pages. Some archaeology in the coming months should get rid of the existing broken ones so that at some point soon-ish the checker shouldn't complain.

**Pull request merged**
