### PR TITLE
Add Meetings pages for annual workshops and other CF related meetings.

### PR DESCRIPTION
**Pull request by ethanrd**
@davidhassell and @erget  - Here's a PR for the Meetings pages we discussed in Thursday's call. For the 2020 Workshop page, I mostly just pulled the text from your draft announcement.

I made it a sub-directory (thought about sub-dirs for each year, maybe later if we need them) but I'm not sure I got the navigation stuff right. I tried to follow the patterns I found but don't have Jekyll setup to run locally so haven't tested that it will build properly. I guess Travis builds on PRs and we can see success or failure but not sure we can look at resulting pages.

### CODE REVIEW

**Comment by erget** [comment]
@davidhassell I fiddled with this and failed - something's up with the build system and the best I could do was undo my own damage by reverting my commits :D Could you have a look? There's lots of files in the branches that the build process goes down to that I think would need updating in order to get it to build properly, but I couldn't find the proper way to do that and am pressed for time today.

**Comment by davidhassell** [comment]
The PR looks good to me. (I'm afraid that I have absolutely no time for looking at the build stuff today, as I'm not in the office.)

**Comment by JonathanGregory** [comment]
Thank you, David. Who is able to merge in this repo? Yes, I noticed the build problem too. I don't see how I could have caused it.

**Comment by JonathanGregory** [comment]
Sorry, my comment was actually referring to David's on my pull request, but the same applies about the build problem.

**Comment by erget** [comment]
@JonathanGregory I could merge this request, however it's not building so I think something's broken. Unfortunately I'm in briefings all day today so I haven't had a chance to investigate it further. My best guess is that it has something to do with changes made during the publishing process of 1.8, as when this is pushed it tries to build the 1.8 documentation and fails. It looks like some build assets need to be copied and adapted to 1.8 before this will succeed, but as I'm not familiar with that part of the build system I prefer not to touch it while I'm not able to investigate more closely.

**Comment by painter1** [comment]
In cf-convention.github.io/Data/cf-conventions/cf-conventions-1.7/ there are many files, notably a makefile, which look like they are used for automatically building documents.  In another branch, add-build-tools-1.8, I copied them to Data/cf-conventions/cf-conventions-1.8/.  There are two directories (besides xxl/) which look like they are only for working data.  I did not copy them  I haven't tried to see whether all this will help; I will look at that tomorrow if possible..

**Comment by erget** [comment]
Hi @painter1 - thanks for looking at this. I fiddled with this as well and was able to get the build to work, but instead of deploying 1.8 as the latest document it deployed 1.7, so I reverted the commits. It'd be worthwhile to understand and document the build system and I'd be willing to contribute to that later on this year. This week unfortunately I'm pretty swamped.

**Pull request merged**
