### PR TITLE
fixes issues with links on WKT page; fixed #83

### LINKED ISSUE #83: On the WKT-Proj Page several Links are not properly formatted in the code
There are several defectively defined links on http://cfconventions.org/wkt-proj-4.html .

I will create a pull request in a few minutes to solve it.

### PR DESCRIPTION
**Pull request by neumannd**
Several links on the page http://cfconventions.org/wkt-proj-4.html
were not working because they were defined as "URL\[URL\]" instead
of "\[URL\]\(URL\)".

### CODE REVIEW

**Comment by davidhassell** [comment]
Looks good to me.

Could I also suggest another minor chang in your PR? Changing `(in support of CF proposal [80](http://cf-trac.llnl.gov/trac/ticket/80))` to `(in support of CF trac ticket [80](http://cf-trac.llnl.gov/trac/ticket/80))` to be consistent with later use in the page (trac #75), and to make it clear that it's not a GitHub issue.

**Comment by erget** [comment]
Doing some cleanup here. @davidhassell @neumannd it looks like this has been stale for quite some time but would be worthwhile finishing up. @davidhassell are you still in favour of this? I've implemented [your editorial suggestion](https://github.com/cf-convention/cf-convention.github.io/pull/84#issuecomment-567065855) and if there's still support for this I propose handling it as a defect and merging.

**Comment by davidhassell** [comment]
Hi @erget,

Yes - still OK with me.

Some of the links appear to be broken. I haven't tried them all, but this one http://www.remotesensing.org/geotiff/proj_list/lambert_conic_conformal_1sp.html no longer resolves. I propose raising these on a new issue after this one is closed, as finding out what the appropriate new links should be goes beyond typsetting and editorial fixes. What do you think?

**Comment by erget** [comment]
@davidhassell good idea, I've tracked the issue with the broken links in #132.

**Pull request merged**
