### PR TITLE
ENH: Enable alias lookup and units lookup

### PR DESCRIPTION
**Pull request by bzah**
## Purpose
This Pull request make it possible to:
- Search standard_name aliases.
- Search (only) canonical units
It also adds a text box that explains how advance searches (regular expressions and logical linked word list) can be used to query the table.

## This PR resolves
- https://github.com/cf-convention/cf-convention.github.io/issues/59 (alias search)
- #200 #27 (units search)

## Technical notes
- The changes include a refactoring of the javascript code to make it more readable/maintainable (sorry for the reviewers).
- The implementation is rudimentary javascript without any library, so not the prettiest but it's lightweight.
- To reduce the amount of changes introduced by this PR we could remove:
  - The python script `generate_html.py` that I used to generate the html (needed to create the demonstrator).
  - The html itself, in case a dedicated tool will be used to generate it by the CF team.

### CODE REVIEW

**Comment by bzah** [comment]
Hi @JonathanGregory, I'm not sure you are the right person to ping here but I would like to make sure this PR get some attention.

**Comment by bzah** [comment]
Dear @japamment 
In the last commits:
- I modified the (current) xls to include the alias search feature in it.
- I added a small python script to transform the xls into a html.
- I also added the resulting html to illustrate the script results.

It seems to work as intended, I was able to test locally the html and the alias search was working fine.
I will remove the python script and the html once we agree on the implementation.

Unfortunately, I'm not sure I will find time to work on unit search (#200) in the near future so I would prefer to merge/close this PR with only these changes.

**Comment by bzah** [comment]
I realize that the current state of the PR include some refactoring (such as extracting the js in a separate file) that might make it hard to review and may be unwanted.
If they are, I can revert those changes.

**Comment by japamment** [comment]
Hi @bzah 

I've taken a look at the pull request - I'm not an expert on xsl code but have tried the Demonstrator and am happy with the results it is producing.

I have one comment about the PR as it stands: I think we don't actually need the Data/generate_html.py script. In the current workflow, the xslt script is initiated using a make file, for example, cf-convention.github.io/Data/cf-standard-names/81/makefile. If it is invoked with
`make cf-standard-name-table`
it first runs the xsltproc command, then a small python script inject-area-type-link.py which, as the name suggests, adds a url to the description of the area_type standard name to point to the area_types table. There is no need to specify a version number as all the processing takes place in the same subdirectory tree (81 in my example).

I plan to rationalise the way that the standard name processing works (the current setup pre-dates our use of GitHub for the website) but for the purposes of this pull request I think it is better to stay consistent with our current workflow.

**Comment by bzah** [comment]
Is there anything I can do to help this PR move forward ? 
If you are looking for an experienced JS dev to review it, I can ask around to try to find someone willing to do it.

**Comment by JonathanGregory** [comment]
Dear Abel @bzah 

Thanks for your patience. I suppose it would be most useful if someone familiar with the existing code reviewed the modification. But if that can't be arranged, I think it should be safe to merge now, since it's already been well-tested. Does anyone object?

Cheers

Jonathan

**Comment by japamment** [comment]
@JonathanGregory @bzah 

I think the original code was written by someone at PCMDI back in about 2006 and it hasn't been changed much since then, so I'm not sure we'll really find a JS expert who is all that familiar with it. My own feeling is that we should merge this change now as it seems to do everything we need. I can then readily incorporate it into the standard names workflow.

Cheers

Alison

**Comment by JonathanGregory** [comment]
@japamment @bzah and I all think it's OK to merge now. Separately Alison has explained that the code was originally written at PCMDI long ago, before we moved to GitHub, so it's unlikely the original author could review it. I will merge this change on Thursday (6th) if no-one objects. I won't do it tomorrow because our US colleagues may not be working today (Tuesday 4th).

**Pull request merged**
