### PR TITLE
Removed .svn directories

### PR DESCRIPTION
**Pull request by ocefpaf**
I believe they were committed in the GitHub repository by mistake.  If this PR is accepted it would be nice to apply a filter branch to remove them from the history.  That will allow for faster clones (and Travis-CI builds).

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
I can't imagine any issues removing these .svn directories.   @mattben , can you?

**Comment by mattben** [comment]
Sorry, for the delay, I wasn't getting updates on this repo.
I don't see why it would hurt to remove that directory. It may be left over from the svn to git conversion, but if it has nothing of value we can remove it from the active tree.

is it a problem that Travis is failing on this PR?

**Comment by ocefpaf** [comment]
> is it a problem that Travis is failing on this PR?

The failure is not related to this PR.  In fact the Travis-CI configuration needs to be re-written.  It is outdated and flawed.

**Comment by mattben** [comment]
:+1:

**Comment by ocefpaf** [comment]
Too old and probably no longer needed.

**Pull request closed without merging**
