### PR TITLE
Fix GHA for testing PRs (see discussion in #103)

### PR DESCRIPTION
**Pull request by ethanrd**
GitHub Action for testing PRs is broken. Discussion and fix in PR #103. That PR may take awhile to get merged so pulling this fix out on its own.

@erget - Can you review this and merge if it looks good?

### CODE REVIEW

**Comment by DocOtak** [comment]
Looks good to me, because this is fixing the GHA it checked itself and that appears to have worked.

**Comment by DocOtak** [comment]
Unfortunately it doesn't seem to fix existing PRs even when you instruct it to rerun the action.

**Comment by ethanrd** [comment]
Yup, they probably need to be rebased on master to pick up the fix. Or we can just merge them even though the test shows them failing.

**Comment by DocOtak** [comment]
I think we should wait for github to be [less full of errors](https://www.githubstatus.com/incidents/6tcfpztf6j9m) before doing trying those.

**Comment by ethanrd** [comment]
Yup, good idea. I'm not getting the 500 responses that I saw earlier. So that seems good.

**Comment by erget** [comment]
@ethanrd @DocOtak looks like I came late to the game - had a 4 day weekend and missed all the action. Thanks for taking care of it! :)

**Pull request merged**
