### PR TITLE
Refactored vocabularies

### PR DESCRIPTION
**Pull request by cofinoa**
@larsbarring, as you have suggested at PR #486  , I have refactored `vocabularies.md` to actual Markdown, instead HTML, and also I have generated automatically some of the lists. 

Jekyll, it's quite limited to manage data and/or strings, and it's needed to create a Jekyll plugin to improve that, but my Ruby skills are also quite limited.

### CODE REVIEW

**Review by larsbarring — COMMENTED** [review]
@cofinoa Many thanks  -- something like this is exactly what I was thinking of. However, I cannot provide any specific input regarding the coding and otherwise changes. THus I leave a detailed review to others.

**Comment by larsbarring** [comment]
The lists of links will be automatically generated from existing version subdirectories under the `../Data/` directory I think that the workflow will be simplified for publishing a new version of the Standard Name Table, Area Type Table (the versions of the Standardized Regions List is hardcoded?).

Hence pinging @japamment, @efisher008

**Comment by JonathanGregory** [comment]
Dear Antonio and Lars

Thanks for working on this issue! It's very helpful. I would like to suggest that it makes the history of what's happened easier to follow if we keep to the practice of putting substantial comments in the issue, rather than PRs. That's because the issue is a continuous record of activity, whereas there can be lots of PRs, including comments on documents that aren't arranged serially.

Best wishes

Jonathan

**Comment by cofinoa** [comment]
@larsbarring I will leave this PR on standby. The auto-generated links to `../Data` has some pitfalls.

**Pull request closed without merging**
